name: Deploy Application Docker Image to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  # =========================
  # CONTINUOUS INTEGRATION
  # =========================
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  # =========================
  # CONTINUOUS DEPLOYMENT
  # =========================
  Continuous-Deployment:
    needs: Continuous-Integration
    runs-on: self-hosted

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (EC2 runner)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Login to Amazon ECR (EC2)
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Stop existing container (if running)
        run: |
          docker rm -f medical-chatbot || true

      - name: Run latest Docker container
        run: |
          docker run -d \
            --name medical-chatbot \
            --restart unless-stopped \
            -p 8080:5000 \
            -e PORT=5000 \
            -e PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
            -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
            -e GOOGLE_API_KEY=${{ secrets.GEMINI_API_KEY }} \
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest
